simRace = 3;
commonTech(true);
addDesign("Swift Heart Class Scout",true,0,5,false);
addDesign("White Falcon Class Cruiser",true,0,10,false);
addDesign("Bright Heart Class Destroyer",true,0,5,false);
addDesign("Bright Heart Light Destroyer",true,1000,5,false);
addDesign("Small Transport",true,0,0,false);
addDesign("Medium Transport",true,250,0,false);
addDesign("Fearless Wing Cruiser",true,0,10,false);
addDesign("Skyfire Class Cruiser",true,0,0,false);
addDesign("Skyfire Class Transport",true,2500,20,false);
addDesign("Valiant Wind Class Carrier",true,0,0,false);
addDesign("Valiant Wind Storm-Carrier",true,1600,5,false);
addDesign("Deth Specula Class Frigate",true,0,10,false);
addDesign("Deth Specula Armoured Frigate",true,1800,10,false);
addDesign("Deth Specula Heavy Frigate",true,1800,20,false);
addDesign("Resolute Class Battlecruiser",true,0,30,false);
addDesign("Red Wind Class Carrier",true,0,5,false);
addDesign("Red Wind Storm-Carrier",true,1500,30,false);
addDesign("Enlighten Class Research Vessel",true,0,15,false);
addDesign("Dark Wing Class Battleship",true,0,80,false);

addDesign("Loki Immunity",false,0,20,false);
addDesign("Super Spy",false,0,25,true);
addDesign("Super Spy Deluxe",false,0,20,false);
cloneShips();
addDesign("Cloak and Intercept",false,0,40,false);
addDesign("Diplomatic Spies",false,1450,5,false);
addDesign("Fortress",false,1500,10,false);
addDesign("Shock Troops",false,1500,10,false);
addDesign("Starbase Fighter Sweeping",false,3800,25,false);
addDesign("Starbase Money Transfer",false,5010,40,false);
// addDesign("Super Spy Command",false,3590,40,false);
addDesign("Super Spy Advanced",false,0,20,false);
addDesign("Super Spy Infiltration",false,1300,10,false);
addDesign("Covert Data Link",false,1200,25,false);
addDesign("Harmonic Weapon Modulation",false,1500,10,false);
//addDesign("Red Storm Cloud",false,3000,40,false);
