simRace = 7;
commonTech(true);
addDesign("Opal Class Torpedo Boat",true,0,0,false);
addDesign("Opal--T Class Torpedo Boat",true,1000,15,false);
addDesign("Ruby Class Light Cruiser",true,0,20,false);
addDesign("Topez Class Gunboat",true,0,0,false);
addDesign("Topaz Class Gunboats",true,600,10,false);
addDesign("Imperial Topaz Class Gunboats",true,750,25,false);
addDesign("Small Transport",true,0,0,false);
addDesign("Medium Transport",true,250,0,false);
addDesign("Sky Garnet Class Destroyer",true,0,0,false);
addDesign("Sky Garnet Class Frigate",true,750,0,false);
addDesign("Sapphire Class Space Ship",true,3900,40,false);
addDesign("Emerald Class Battlecruiser",true,0,30,false);
addDesign("Onyx Class Frigate",true,0,15,false);
addDesign("Pyrite Class Frigate",true,600,50,false);
addDesign("Selenite Class Battlecruiser",true,4000,30,false);
addDesign("Diamond Flame Class Battleship",true,0,20,false);
addDesign("Crystal Thunder Class Carrier",true,0,30,false);

addDesign("Desert Worlds",false,0,10,true);
addDesign("Tow Capture",false,0,30,false);
addDesign("Web Mines",false,0,165,true);
addDesign("Improved Desert Habitation",false,2900,30,false);
addDesign("Starbase Mine Laying",false,4400,30,false);
addDesign("Starbase Mine Sweeping",false,3150,15,false);
// addDesign("Minefields Save Fuel",false,0,0,false);
