simRace = 6;
commonTech(true);
addDesign("B200 Class Probe",true,0,10,false);
addDesign("B41 Explorer",true,0,0,false);
addDesign("B41b Explorer",true,400,20,false);
addDesign("Iron Slave Class Baseship",true,0,0,false);
addDesign("Iron Slave Class Tug",true,800,0,false);
addDesign("B222 Destroyer",true,0,0,false);
addDesign("B222b Destroyer",true,1300,40,false);
addDesign("Firecloud Class Cruiser",true,0,140,false);
addDesign("Lorean Class Temporal Lance",true,4320,35,false);
addDesign("Biocide Class Carrier",true,0,65,false);
addDesign("Annihilation Class Battleship",true,0,40,false);
addDesign("Dungeon Class Stargate",true,3880,10,false);

addDesign("Assimilation",false,0,70,true);
addDesign("Recover Minerals",false,0,5,false);
addDesign("Repair Self",false,0,10,true);
cloneShips();
addDesign("Starbase Mine Laying",false,4400,30,false);
addDesign("Starbase Mine Sweeping",false,3150,15,false);
