simRace = 4;
commonTech(true);
addDesign("D7a Painmaker Class Cruiser",true,0,0,false);
addDesign("D7b Painmaker Class Cruiser",true,900,15,false);
addDesign("Little Pest Class Escort",true,0,0,false);
addDesign("Little Pest Light Escort",true,500,0,false);
addDesign("D7 Coldpain Class Cruiser",true,0,10,false);
addDesign("Small Transport",true,0,0,false);
addDesign("Medium Transport",true,250,0,false);
addDesign("Armored Ore Condenser",true,900,10,false);
addDesign("Ill Wind Class Battlecruiser",true,0,20,false);
addDesign("D3 Thorn Class Destroyer",true,0,5,false);
addDesign("D3 Thorn Class Frigate",true,1100,10,false);
addDesign("D3 Thorn Class Cruiser",true,1750,20,false);
addDesign("D19b Nefarious Class Destroyer",true,0,35,false);
addDesign("D19c Nefarious Class Destroyer",true,1800,40,false);
addDesign("Deth Specula Class Frigate",true,0,10,false);
addDesign("Deth Specula Armoured Frigate",true,1800,10,false);
addDesign("Deth Specula Stealth",true,2800,30,false);
addDesign("Saber Class Frigate",true,0,35,false);
addDesign("Saber Class Shield Generator",true,3300,50,false);
addDesign("D9 Usva Class Stealth Raider",true,3000,20,false);
addDesign("Victorious Class Battleship",true,0,20,false);

addDesign("5X Ground Defense",false,0,10,true);
addDesign("15X Ground Combat",false,0,20,true);
addDesign("Pillage Planet",false,0,40,true);
addDesign("Planet Immunity",false,0,30,true);
cloneShips();
addDesign("2X Faster Beams",false,0,60,false);
addDesign("Plunder Planet",false,2250,30,false);
addDesign("Starbase Mine Laying",false,4400,30,false);
addDesign("Starbase Mine Sweeping",false,3150,15,false);
