simRace = 2;
commonTech(true);
addDesign("Reptile Class Destroyer",true,0,5,false);
addDesign("Reptile Class Escort",true,500,5,false);
addDesign("Eros Class Research Vessel",true,0,15,false);
addDesign("Lizard Class Cruiser",true,0,20,false);
addDesign("Vendetta Class Frigate",true,0,0,false);
addDesign("Vendetta B Class Frigate",true,1400,0,false);
addDesign("Vendetta Stealth Class Frigate",true,900,5,false);
addDesign("Saurian Class Light Cruiser",true,0,10,false);
addDesign("Saurian Class Frigate",true,850,10,false);
addDesign("Saurian Class Heavy Frigate",true,1050,20,false);
addDesign("Loki Class Destroyer",true,0,40,false);
addDesign("Chameleon Class Freighter",true,2600,20,false);
addDesign("Madonnzila Class Carrier",true,0,10,false);
addDesign("Madonnzila Class Carrier (C)",true,4200,25,false);
addDesign("T-Rex Class Battleship",true,0,20,false);
addDesign("T-Rex Class Battleship (C)",true,3500,35,false);
addDesign("Zilla Class Battlecarrier",true,2500,15,false);

addDesign("15X Ground Defense",false,0,20,true);
addDesign("30X Ground Combat",false,0,40,true);
addDesign("200% Mining",false,0,50,true);
addDesign("Hisssss!",false,0,50,true);
addDesign("Lizard Crew Bonus",false,0,30,true);
addDesign("Loki Immunity",false,0,20,false);
cloneShips();
addDesign("Starbase Mine Laying",false,4400,30,false);
addDesign("Starbase Mine Sweeping",false,3150,15,false);
