simRace = 5;
commonTech(true);
addDesign("Br4 Class Gunship",true,0,25,false);
addDesign("Outrider Class Scout",true,0,0,false);
addDesign("Outrider Class Transport",true,500,0,false);
addDesign("Little Pest Class Escort",true,0,0,false);
addDesign("Little Pest Light Escort",true,500,0,false);
addDesign("Dwarfstar Class Transport",true,0,5,false);
addDesign("Dwarfstar II Class Transport",true,1800,10,false);
addDesign("Br5 Kaye Class Torpedo Boat",true,0,30,false);
addDesign("Small Transport",true,0,0,false);
addDesign("Medium Transport",true,250,0,false);
addDesign("D3 Thorn Class Destroyer",true,0,5,false);
addDesign("Lady Royale Class Cruiser",true,0,10,false);
addDesign("Meteor Class Blockade Runner",true,0,90,false);
addDesign("Skyfire Class Cruiser",true,0,0,false);
addDesign("Skyfire Class Transport",true,2500,20,false);
addDesign("Red Wind Class Carrier",true,0,5,false);
addDesign("Red Wind Storm-Carrier",true,1500,30,false);
addDesign("Hikos Armored Trailer",true,1000,0,false);
addDesign("Bloodfang Class Carrier",true,0,0,false);
addDesign("Bloodfang Stealth Class Carrier",true,4800,10,false);

addDesign("3X Beam Crew Kill",false,0,10,false);
addDesign("Rob Ship",false,0,120,true);
addDesign("Tow Capture",false,0,30,false);
addDesign("Hide In Warp Well",false,750,20,false);
addDesign("Pleasure Planets",false,1500,20,false);
addDesign("Rob Fighters",false,2000,50,false);
addDesign("Shock Troops",false,1500,10,false);
addDesign("Starbase Mine Laying",false,4400,30,false);
addDesign("Starbase Mine Sweeping",false,3150,15,false);
