simRace = 10;
commonTech(true);
addDesign("Taurus Class Scout",true,0,0,false);
addDesign("Taurus Class Transport",true,500,0,false);
addDesign("Falcon Class Escort",true,0,40,false);
addDesign("Gaurdian Class Destroyer",true,0,0,false);
addDesign("Gaurdian B Class Destroyer",true,1300,0,false);
addDesign("Gaurdian C Class Destroyer",true,1300,0,false);
addDesign("Armored Transport",true,0,0,false);
addDesign("Heavy Armored Transport",true,350,0,false);
addDesign("Sage Class Frigate",true,0,0,false);
addDesign("Sage Class Repair Ship",true,0,10,false);
addDesign("Tranquility Class Cruiser",true,0,10,false);
addDesign("Iron Lady Class Frigate",true,0,0,false);
addDesign("Iron Lady Class Command Ship",true,2900,50,false);
addDesign("Rush Class Heavy Carrier",true,0,50,false);

addDesign("Arctic Planet Colonies",false,0,20,true);
addDesign("Build Fighters",false,0,100,true);
addDesign("Dark Sense Defense",false,0,5,true);
addDesign("Planet Immunity",false,0,30,true);
addDesign("Rebel Ground Attack",false,0,30,true);
cloneShips();
addDesign("Energy Defense Field",false,4700,40,false);
addDesign("Hide In Warp Well",false,750,20,false);
addDesign("Shock Troops",false,1500,10,false);
addDesign("Starbase Mine Laying",false,4400,30,false);
addDesign("Starbase Mine Sweeping",false,3150,15,false);
