simRace = 9;
commonTech(true);
addDesign("Cat's Paw Class Destroyer",true,0,20,false);
addDesign("Iron Slave Class Baseship",true,0,0,false);
addDesign("Iron Slave Class Tug",true,800,0,false);
addDesign("Pawn Class Baseship",true,0,5,false);
addDesign("Pawn B Class Baseship",true,1300,10,false);
addDesign("Cybernaut Class Baseship",true,0,0,false);
addDesign("Cybernaut B Class Baseship",true,1900,10,false);
addDesign("Armored Ore Condenser",true,900,10,false);
addDesign("Sage Class Frigate",true,1700,0,false);
addDesign("Sage Class Repair Ship",true,1700,10,false);
addDesign("Instrumentality Class Baseship",true,0,30,false);
addDesign("Automa Class Baseship",true,0,40,false);
addDesign("Golem Class Baseship",true,0,50,false);

addDesign("4X Mine Laying",false,0,60,true);
addDesign("Build Fighters",false,0,100,true);
addDesign("Star Cluster Radiation Immunity",false,0,10,true);
cloneShips();
// addDesign("Minefields Save Fuel",false,0,0,false);
addDesign("Build Clans",false,1024,30,false);
addDesign("Dense Minefields",false,3000,25,false);
addDesign("Fortress",false,1500,10,false);
addDesign("Hardened Mines",false,2000,25,false);
addDesign("Internal Temp Regulation",false,2000,30,false);
addDesign("Starbase Mine Sweeping",false,3150,15,false);
addDesign("Starbase Money Transfer",false,5010,40,false);
