const shuffler = "Alien";

const itemCollection = [
	{nameeS:"SoyPurp", nameeL:"Soylent Purple"},
	{nameeS:"AMW", nameeL:"Anti-Matter Warhead"},
	{nameeS:"ITC", nameeL:"Interlinked Targeting Computer"},
	{nameeS:"Polyalloy", nameeL:"Polytitanium Alloy"},
	{nameeS:"LLT", nameeL:"Long Lance Torpedo"},
	{nameeS:"CenComp", nameeL:"Central Computer"},
	{nameeS:"RD", nameeL:"Resupply Depot"},
	{nameeS:"Holodeck", nameeL:"Holodeck"},
	{nameeS:"CFD", nameeL:"Cold Fusion Drive"},
	{nameeS:"EA", nameeL:"Emissive Armor"},
	{nameeS:"EWM", nameeL:"Electronic Warfare Module"},
	{nameeS:"Microwarp", nameeL:"Microwarp Drive"},
	{nameeS:"CS", nameeL:"Combat Sensors"},
	{nameeS:"Burn", nameeL:"Afterburners"},
	{nameeS:"Photon", nameeL:"Photon Bomb"},
	{nameeS:"Stim", nameeL:"Stim Packs"},
	{nameeS:"ICQ", nameeL:"Improved Crew Quarters"},
	{nameeS:"PWC", nameeL:"Phased Warp Coil"},
	{nameeS:"AOSS", nameeL:"Advanced Ordnance Storage System"},
	{nameeS:"CapChair", nameeL:"The Captain's Chair"},
	{nameeS:"EffFact", nameeL:"Efficient Factories"},
	{nameeS:"Omega", nameeL:"Omega Crystals"},
	{nameeS:"CryoPods", nameeL:"Cryogenic Stasis Pods"},
	{nameeS:"SWJam", nameeL:"Minesweep Jammer"},
	{nameeS:"AirSupp", nameeL:"Air Support"},
	{nameeS:"HidTurr", nameeL:"Hidden Turret"},
	{nameeS:"StealthFE", nameeL:"Stealth Field Emitter"},
	{nameeS:"AdvComm", nameeL:"Advanced Comm Array"},
	{nameeS:"ManalysisBay", nameeL:"Mobile Analysis Bay"},
	{nameeS:"ACD", nameeL:"Adaptive Cloaking Device"},
	{nameeS:"Workshop", nameeL:"On Board Workshop"},
	{nameeS:"Highway", nameeL:"Superhighway"},
	{nameeS:"SSPS", nameeL:"Self-Sustaining Power Source"},
	{nameeS:"AdvSY", nameeL:"Advanced Shipyards"},
	{nameeS:"Lorelei", nameeL:"Lorelei System"},
	{nameeS:"WepCache", nameeL:"Advanced Weapons Cache"},
	{nameeS:"QuanComp", nameeL:"Quantum Computing"},
	{nameeS:"FocuPhaser", nameeL:"Focused Phasers"},
	{nameeS:"SkipMsles", nameeL:"Skipper Missiles"},
	{nameeS:"Bioweps", nameeL:"Bioweapons"},
	{nameeS:"AegisFF", nameeL:"Aegis Frigate"},
	{nameeS:"WarFF", nameeL:"War Frigate"}];
