const shuffler = "Crew";

const itemCollection = [
	{nameeS:"Gov", nameeL:"Governor"},
	{nameeS:"SecOff", nameeL:"Security Officer"},
	{nameeS:"DConOff", nameeL:"Damage Control Officer"},
	{nameeS:"Ensign", nameeL:"Ensign Expendable"},
	{nameeS:"Hero", nameeL:"Hero"},
	{nameeS:"Engi", nameeL:"Engineer"},
	{nameeS:"AstNavi", nameeL:"Asteroid Navigator"},
	{nameeS:"NebNavi", nameeL:"Nebula Navigator"},
	{nameeS:"Helm", nameeL:"Helmsmen"},
	{nameeS:"SuppOff", nameeL:"Supply Officer"},
	{nameeS:"Def", nameeL:"Defender"},
	{nameeS:"Tac", nameeL:"Tactician"},
	{nameeS:"Strat", nameeL:"Strategist"},
	{nameeS:"FirstOff", nameeL:"First Officer"},
	{nameeS:"TacOff", nameeL:"Tactical Officer"},
	{nameeS:"Cap", nameeL:"Captain"},
	{nameeS:"WepOff", nameeL:"Weapons Officer"},
	{nameeS:"HWOff", nameeL:"Heavy Weapons Officer"},
	{nameeS:"SciOff", nameeL:"Science Officer"},
	{nameeS:"MarCap", nameeL:"Marine Captain"},
	{nameeS:"PlanAdm", nameeL:"Planetary Admiral"},
	{nameeS:"NavyAdm", nameeL:"Admiral of the Navy"},
	{nameeS:"FleetAdm", nameeL:"Fleet Admiral"},
	{nameeS:"Adm", nameeL:"Admiral"},
	{nameeS:"Comma", nameeL:"Commander"},
	{nameeS:"RearAdm", nameeL:"Rear Admiral"},
	{nameeS:"Staff", nameeL:"General Staff"},
	{nameeS:"OrdTec", nameeL:"Ordnance Technician"},
	{nameeS:"WarOff", nameeL:"Warrant Officer"},
	{nameeS:"SquadLdr", nameeL:"Squadron Leader"},
	{nameeS:"CAG", nameeL:"CAG"},
	{nameeS:"DCC", nameeL:"Deck Crew Chief"},
	{nameeS:"GunOff", nameeL:"Gunnery Officer"},
	{nameeS:"Commo", nameeL:"Commodore"},
	{nameeS:"MarComma", nameeL:"Marine Commander"},
	{nameeS:"MarLieu", nameeL:"Marine Lieutenant"},
	{nameeS:"SWT", nameeL:"Special Warfare Technician"},
	{nameeS:"ChiEngi", nameeL:"Chief Engineer"},
	{nameeS:"PatLdr", nameeL:"Patrol Leader"},
	{nameeS:"AstOff", nameeL:"Astrometrics Officer"},
	{nameeS:"OpOff", nameeL:"Operations Officer"},
	{nameeS:"Mycroft", nameeL:"Mycroft"},
	{nameeS:"Queen", nameeL:"Hive Queen"},
	{nameeS:"Hal", nameeL:"Hal 10K"},
	{nameeS:"ROM", nameeL:"ROMmie"},
	{nameeS:"WOPR", nameeL:"QOPR"},
	{nameeS:"Data", nameeL:"Data"},
	{nameeS:"Skynet", nameeL:"Skynet"},
	{nameeS:"Quorra", nameeL:"Quorra"},
	{nameeS:"Smith", nameeL:"Agent Smith"},
	{nameeS:"Ash", nameeL:"Ash"},
	{nameeS:"Alexa", nameeL:"Alexa"},
	{nameeS:"Sonnny", nameeL:"Sonny"}];
