const shuffler = "DSPA";

const itemCollection = [
	{nameeS:"Aggro", nameeL:"Aggressive"},
	{nameeS:"Spice", nameeL:"Spice"},
	{nameeS:"Organia", nameeL:"Organia"},
	{nameeS:"Dilithium", nameeL:"Dilithium Crystals"},
	{nameeS:"Abundant", nameeL:"Abundant"},
	{nameeS:"Wealthy", nameeL:"Wealthy"},
	{nameeS:"Poor", nameeL:"Poor"},
	{nameeS:"Desolate", nameeL:"Desolate"},
	{nameeS:"Sparta", nameeL:"Sparta"},
	{nameeS:"Defensible", nameeL:"Defensible"},
	{nameeS:"Dampening", nameeL:"Dampening"},
	{nameeS:"Ambush", nameeL:"Ambush"},
	{nameeS:"Doomed", nameeL:"Doomed"},
	{nameeS:"Builder", nameeL:"Builder"},
	{nameeS:"Spaceport", nameeL:"Spaceport"},
	{nameeS:"Research", nameeL:"Research"},
	{nameeS:"MinorTech", nameeL:"Minor Technology"},
	{nameeS:"MajorTech", nameeL:"Major Technology"},
	{nameeS:"Cloaked", nameeL:"Cloaked"},
	{nameeS:"Ranged", nameeL:"Ranged"},
	{nameeS:"Accurate", nameeL:"Accurate"},
	{nameeS:"Shielded", nameeL:"Shielded"},
	{nameeS:"Giant", nameeL:"Giant"},
	{nameeS:"Geniuses", nameeL:"Military Geniuses"},
	{nameeS:"Jedun", nameeL:"Jedun"},
	{nameeS:"Telepathic", nameeL:"Telepathic"},
	{nameeS:"Scanning", nameeL:"Scanning"},
	{nameeS:"Dilation", nameeL:"Time Dilation"}];
