const shuffler = "Empire";

const itemCollection = [
	{nameeS:"Fearless", nameeL:"Fearless Race"},
	{nameeS:"Warrior", nameeL:"Warrior Race"},
	{nameeS:"Celestial", nameeL:"Celestial Knights"},
	{nameeS:"Giant", nameeL:"Giant Race"},
	{nameeS:"Industrious", nameeL:"Industrious Race"},
	{nameeS:"Ancient", nameeL:"Ancient Race"},
	{nameeS:"Pilgrims", nameeL:"Space Pilgrims"},
	{nameeS:"Hive", nameeL:"Hive Mind"},
	{nameeS:"Nano", nameeL:"Nano-technology"},
	{nameeS:"Quick", nameeL:"Quick Learners"},
	{nameeS:"Gifted", nameeL:"Gifted Scientists"},
	{nameeS:"Engineers", nameeL:"Master Engineers"},
	{nameeS:"Insect", nameeL:"Insectoids"},
	{nameeS:"Immortals", nameeL:"Immortals"},
	{nameeS:"Tact", nameeL:"Expert Tacticians"},
	{nameeS:"Horsemen", nameeL:"Horsemen of the Plains"},
	{nameeS:"Swords", nameeL:"And We Still Carry Swords"},
	{nameeS:"Diplomats", nameeL:"Amazing Diplomats"},
	{nameeS:"Traders", nameeL:"Traders"},
	{nameeS:"Cloaking", nameeL:"Cloaking Geniuses"},
	{nameeS:"Wolves", nameeL:"Star Wolves"},
	{nameeS:"PttP", nameeL:"Power to the People"},
	{nameeS:"Speed", nameeL:"House of Speed"},
	{nameeS:"Psychics", nameeL:"Powerful Psychics"},
	{nameeS:"Shifters", nameeL:"Shape Shifters"},
	{nameeS:"Move", nameeL:"On the Move"},
	{nameeS:"Longbow", nameeL:"Longbowmen"},
	{nameeS:"Sun", nameeL:"War Sun"},
	{nameeS:"Salvage", nameeL:"Salvage Experts"},
	{nameeS:"Berserker", nameeL:"Berserker Genome"},
	{nameeS:"Robot", nameeL:"Robot Race"},
	{nameeS:"CAgates", nameeL:"Masters of the Gates"},
	{nameeS:"Fast", nameeL:"Fast Replicators"},
	{nameeS:"Green", nameeL:"Green Replicators"},
	{nameeS:"Gunnery", nameeL:"Improved Gunnery"},
	{nameeS:"Warp", nameeL:"Warp Gates"},
	{nameeS:"Research", nameeL:"Advanced Research"},
	{nameeS:"Capitol", nameeL:"Replicator Capitol"}];
