const shuffler = "Resource";

const itemCollection = [
	{nameeS:"Red", nameeL:"Red Squadron"},
	{nameeS:"Blind", nameeL:"Sensor Blind Spot"},
	{nameeS:"SD", nameeL:"Self-Destruct"},
	{nameeS:"Conceal", nameeL:"Concealed Minefield"},
	{nameeS:"HeroicSC", nameeL:"Heroic Ships (SC/DD)"},
	{nameeS:"HeroicCA", nameeL:"Heroic Ships (CA/BD)"},
	{nameeS:"HeroicBC", nameeL:"Heroic Ships (BC/Raider)"},
	{nameeS:"HeroicBB", nameeL:"Heroic Ships (BB/BV)"},
	{nameeS:"HeroicGr", nameeL:"Heroic Ground Unit"},
	{nameeS:"Familiar", nameeL:"Defending Familiar Terrain"},
	{nameeS:"Breakthru", nameeL:"Research Breakthrough"},
	{nameeS:"Quick", nameeL:"Quick Study"},
	{nameeS:"Ancient", nameeL:"Discover Member of Ancient Race"},
	{nameeS:"Overload", nameeL:"Overload Weapons"},
	{nameeS:"Boarding", nameeL:"Unconventional Boarding"},
	{nameeS:"Xeno", nameeL:"Xeno-Archeology"},
	{nameeS:"Missed", nameeL:"Missed Rendezvous"},
	{nameeS:"Monstrosity", nameeL:"Activate Space Monstrosity"},
	{nameeS:"DM", nameeL:"Spawn Doomsday Machine"},
	{nameeS:"Spy", nameeL:"Spy on Board"},
	{nameeS:"Cover", nameeL:"Provide Cover"},
	{nameeS:"Reinforcements", nameeL:"Alien Reinforcements"},
	{nameeS:"DCO", nameeL:"Deep Cover Operative"},
	{nameeS:"Diplomats", nameeL:"Amazing Diplomats"},
	{nameeS:"Shutdown", nameeL:"Forced System Shutdown"},
	{nameeS:"Smuggle", nameeL:"Smuggler's Route"},
	{nameeS:"Bombard", nameeL:"Planetary Bombardment"},
	{nameeS:"Charts", nameeL:"Update Your Charts"},
	{nameeS:"Dead", nameeL:"Play Dead"},
	{nameeS:"Overcon", nameeL:"Overconfidence"},
	{nameeS:"HidPow", nameeL:"Hidden Power"},
	{nameeS:"Sanctions", nameeL:"Sanctions"},
	{nameeS:"Coup", nameeL:"Coup"},
	{nameeS:"Retreat", nameeL:"Retreat When Engaged"},
	{nameeS:"Collateral", nameeL:"Collateral Damage"},
	{nameeS:"Minerals", nameeL:"Minerals +5/-3"},
	{nameeS:"Splash", nameeL:"Splash Damage"},
	{nameeS:"WhereNoOne", nameeL:"Where No Man Has Gone Before"},
	{nameeS:"Slingshot", nameeL:"Time Travel Slingshot"},
	{nameeS:"Babel", nameeL:"Journey to Babel"},
	{nameeS:"Terror", nameeL:"Balance of Terror"},
	{nameeS:"Below", nameeL:"Creature from Below"},
	{nameeS:"Arena", nameeL:"Arena"},
	{nameeS:"SurveyD", nameeL:"Difficult Planet Survey"},
	{nameeS:"SurveyE", nameeL:"Easy Planet Survey"},
	{nameeS:"SurveyS", nameeL:"Scientific Survey"},
	{nameeS:"AnomalyS", nameeL:"Stellar Anomaly Investigation"},
	{nameeS:"Distress", nameeL:"Distress Call"},
	{nameeS:"Riots", nameeL:"Quell Riots"},
	{nameeS:"Police", nameeL:"Police State"},
	{nameeS:"FTL", nameeL:"New FTL Test"},
	{nameeS:"AnomalyD", nameeL:"Dimensional Anomaly"},
	{nameeS:"Asteroid", nameeL:"Asteroid Strike"},
	{nameeS:"SurveyU", nameeL:"Urgent Deep Space Survey"},
	{nameeS:"Survivors", nameeL:"Survivors"},
	{nameeS:"Father", nameeL:"Sins of the Father"},
	{nameeS:"Outpost", nameeL:"Defend an Outpost"},
	{nameeS:"Privateers", nameeL:"Privateers"},
	{nameeS:"Virus", nameeL:"Virus"},
	{nameeS:"Sabotage", nameeL:"Sabotage"},
	{nameeS:"Population", nameeL:"Population +/-"}];
