const shuffler = "Scenario";

const itemCollection = [
	{nameeS:"Carthage", nameeL:"Carthage"},
	{nameeS:"Fruitful", nameeL:"Fruitful"},
	{nameeS:"Effort", nameeL:"Worth the Effort"},
	{nameeS:"Extinct", nameeL:"Extinct Alien Empire"},
	{nameeS:"Expert", nameeL:"Expert Empires"},
	{nameeS:"NoSensors", nameeL:"No Sensor Lock Possible"},
	{nameeS:"Thick", nameeL:"Thick Asteroids"},
	{nameeS:"AdvNav", nameeL:"Advanced Navigation"},
	{nameeS:"Expensive", nameeL:"Expensive Ships"},
	{nameeS:"PlanetGates", nameeL:"Planetary Gates"},
	{nameeS:"AWayThru", nameeL:"A Way Through"},
	{nameeS:"Better", nameeL:"Better Homes"},
	{nameeS:"ImpCO", nameeL:"Improved Colony Ships"},
	{nameeS:"Close", nameeL:"Close Quarters"},
	{nameeS:"Tractor", nameeL:"Big Ships and Tractor Beams"},
	{nameeS:"ShieldProj", nameeL:"Big Ships and Shield Projectors"},
	{nameeS:"AdvDD", nameeL:"Advanced Destroyers"},
	{nameeS:"BCU", nameeL:"Battlecarrier Universica"},
	{nameeS:"AdvR", nameeL:"Advanced Raiders"},
	{nameeS:"AdvBase", nameeL:"Advanced Bases"},
	{nameeS:"ToughPlan", nameeL:"Tough Planets"},
	{nameeS:"ToughSY", nameeL:"Tough Shipyards"},
	{nameeS:"STran", nameeL:"Stealth Transports"},
	{nameeS:"Ion", nameeL:"Ion Cannons"},
	{nameeS:"White", nameeL:"We Need the White"},
	{nameeS:"DM", nameeL:"Doomsday Machine"},
	{nameeS:"Amoeba", nameeL:"Space Amoeba"},
	{nameeS:"Heavy", nameeL:"Heavy Terrain"},
	{nameeS:"Safer", nameeL:"Safer Space"},
	{nameeS:"Smart", nameeL:"Smart Scientists"},
	{nameeS:"Trained", nameeL:"Trained Defenders"},
	{nameeS:"Weakness", nameeL:"Know the Weakness"},
	{nameeS:"NoTP", nameeL:"No temporal Prime Directive"},
	{nameeS:"Bloody", nameeL:"Bloody Combat"},
	{nameeS:"Experienced", nameeL:"Experienced Crew"},
	{nameeS:"Complicated", nameeL:"Life is Complicated"},
	{nameeS:"Rich", nameeL:"Rich Minerals"},
	{nameeS:"HeadStart", nameeL:"Technology Head Start"},
	{nameeS:"LowMaint", nameeL:"Low Maintenance"},
	{nameeS:"Weak", nameeL:"Weak NPAs"},
	{nameeS:"Hardy", nameeL:"Hardy Empires"},
	{nameeS:"Second", nameeL:"Second Salvo"},
	{nameeS:"Recon", nameeL:"Recon Ships"}];
